name: project_magang
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.0 <3.3.0'

dependencies: 
  auto_size_text: ^3.0.0
  cloud_firestore: ^3.1.1
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.2
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  firebase_storage: ^10.3.8
  firebase_storage_web: ^3.3.6
  floating_bottom_navigation_bar: ^1.5.2
  focused_menu: ^1.0.5
  footer: ^0.0.4
  geolocator: any
  get: 4.6.5
  hexcolor: ^2.0.7
  iconly: ^1.0.1
  image_picker: 0.8.5+3
  image_picker_for_web: ^2.1.8
  geocoding: 2.0.5
  intl: 0.17.0
  flutter_keyboard_visibility: 5.4.0
  form_field_validator: 1.1.0
  flutter_map: 3.0.0
  flutter_map_location_marker: any
  flutter_compass: any
  latlong2: any
  vector_map_tiles: 3.0.2
  syncfusion_flutter_datepicker: 20.3.50
  syncfusion_localizations: any
  splashscreen: 1.3.5
  animated_splash_screen: 1.3.0
  flutter_screenutil: 5.6.0
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

dev_dependencies: 
  flutter_native_splash: 2.2.12
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_native_splash: 
  image: assets/icons/iconMonetin.png
  color: '#0E3566'
  android_12: 
    image: assets/icons/iconMonetin.png
    color: '#0E3566'

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  fonts: 
    - family: CustomIconLogin
      fonts: 
        - asset: fonts/CustomIconLogin.ttf
    - family: CustomIconHome
      fonts: 
        - asset: fonts/CustomIconHome.ttf
    - family: CustomIconAll
      fonts: 
        - asset: fonts/CustomIconAll.ttf
  uses-material-design: true

