name: project_magang
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^3.1.1
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.2
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  floating_bottom_navigation_bar: ^1.5.2
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.4
  focused_menu: ^1.0.5
  footer: ^0.0.4
  get: 4.6.5
  hexcolor: ^2.0.7
  iconly: ^1.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: CustomIconLogin
      fonts:
        - asset: fonts/CustomIconLogin.ttf
    - family: CustomIconHome
      fonts:
        - asset: fonts/CustomIconHome.ttf
    - family: CustomIconAll
      fonts:
        - asset: fonts/CustomIconAll.ttf
