name: project_magang
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  auto_size_text: ^3.0.0
  cloud_firestore: ^3.1.1
  cupertino_icons: ^1.0.2
  dropdown_search: ^5.0.2
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  firebase_storage: ^10.3.8
  firebase_storage_web: ^3.3.6
  floating_bottom_navigation_bar: ^1.5.2
  flutter_native_splash: ^2.2.4
  focused_menu: ^1.0.5
  footer: ^0.0.4
  geolocator: any
  get: 4.6.5
  google_maps_flutter: ^2.2.0
  hexcolor: ^2.0.7
  iconly: ^1.0.1
  image_picker: 0.8.5+3
  image_picker_for_web: ^2.1.8
  geocoding: 2.0.5
  intl: 0.17.0
  flutter_keyboard_visibility: 5.4.0
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/icons/
    - assets/images/
  fonts: 
    - family: CustomIconLogin
      fonts: 
        - asset: fonts/CustomIconLogin.ttf
    - family: CustomIconHome
      fonts: 
        - asset: fonts/CustomIconHome.ttf
    - family: CustomIconAll
      fonts: 
        - asset: fonts/CustomIconAll.ttf
  uses-material-design: true

