/// Flutter icons CustomIconHome
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconHome
///      fonts:
///       - asset: fonts/CustomIconHome.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class CustomIconHome {
  CustomIconHome._();

  static const _kFontFam = 'CustomIconHome';
  static const String? _kFontPkg = null;

  static const IconData attendance = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData setting = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_1 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData checklist = IconData(0xf301, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xf353, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xf35e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xf38c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData file = IconData(0xf398, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
