/// Flutter icons CustomIconLogin
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIconLogin
///      fonts:
///       - asset: fonts/CustomIconLogin.ttf
///
/// 
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
///
import 'package:flutter/widgets.dart';

class CustomIconLogin {
  CustomIconLogin._();

  static const _kFontFam = 'CustomIconLogin';
  static const String? _kFontPkg = null;

  static const IconData lock = IconData(0xf319, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_closed = IconData(0xf366, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tools = IconData(0xf380, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xf394, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData organization = IconData(0xf3a7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xf3a8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData person = IconData(0xf3c8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
